apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: cylindrical-server
build:
  artifacts:
    - image: rg.fr-par.scw.cloud/sebastienprudhomme/cylindrical-server
      docker:
        dockerfile: Dockerfile.dev
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - kubernetes/*.yaml
portForward:
  - resourceType: service
    resourceName: argo-server
    namespace: argo
    port: 2746
  - resourceType: service
    resourceName: minio
    namespace: minio
    port: 9000
