apiVersion: apps/v1
kind: Deployment
metadata:
  name: cylindrical-server
  namespace: cylindrical
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cylindrical-server
      app.kubernetes.io/instance: cylindrical-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cylindrical-server
        app.kubernetes.io/instance: cylindrical-server
    spec:
      serviceAccountName: cylindrical-server
      containers:
        - name: cylindrical-server
          image: rg.fr-par.scw.cloud/sebastienprudhomme/cylindrical-server
          env:
            - name: MINIO_END_POINT
              value: minio.minio
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: secretkey
          ports:
            - name: http
              containerPort: 3030
              protocol: TCP
