apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cylindrical-server
  namespace: cylindrical
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cylindrical-server
subjects:
  - kind: ServiceAccount
    name: cylindrical-server
    namespace: cylindrical
