apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cylindrical-server
  namespace: cylindrical
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - create
      - get
      - list
