apiVersion: v1
kind: Service
metadata:
  name: cylindrical-server
  namespace: cylindrical
spec:
  type: ClusterIP
  ports:
    - port: 3030
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: cylindrical-server
    app.kubernetes.io/instance: cylindrical-server
